// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";

import { Poppins } from "next/font/google";
import { Toaster } from "sonner";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Baymax",
  description: "Generated by create next app",
  icons:{
    icon:'/img (1).png'
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}  cz-shortcut-listen="true">
      <Toaster position="top-right" />
        {children}
      </body>
    </html>
  );
}
